apiVersion: v2
appVersion: "1.0"
description: Family Private Law - Document Generator Service
name: fprl-dgs
version: 0.0.1
dependencies:
    - name: java
      version: ~3.4.5
      repository: "@hmctspublic"
