java:
    applicationPort: 4007
    aadIdentityName: fprl
    ingressHost: "fprl-dgs-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    environment:
        AUTH_PROVIDER_SERVICE_CLIENT_BASEURL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        EVIDENCE_MANAGEMENT_CLIENT_API_BASEURL: "http://div-emca-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        IDAM_S2S_URL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        DOCMOSIS_SERVICE_BASE_URL: "https://docmosis.aat.platform.hmcts.net"
        REFORM_SERVICE_NAME: "fprl"
        REFORM_TEAM: "fprl"
        AUTH_PROVIDER_SERVICE_CLIENT_MICROSERVICE: "fprl-dgs-api"
        AUTH_PROVIDER_SERVICE_CLIENT_TOKENTIMETOLIVEINSECONDS: "900"
        EVIDENCE_MANAGEMENT_CLIENT_API_HEALTH_ENDPOINT: "/health"
    keyVaults:
        "fprl":
            resourceGroup: fprl
            secrets:
                - fprl-doc-s2s-auth-secret
                - docmosis-api-key
                - AppInsightsInstrumentationKey


