server:
    port: ${DIV_DOCUMENT_GENERATOR_PORT:4007}

service:
    pdf-service:
        uri: ${PDF_SERVICE_BASEURL:http://localhost:5500}/pdfs
        health:
            uri: ${PDF_SERVICE_BASEURL:http://localhost:5500}/health
    evidence-management-client-api:
        uri: ${EVIDENCE_MANAGEMENT_CLIENT_API_BASEURL:http://localhost:4006}/emclientapi/version/1/upload
        health:
            context-path: ${EVIDENCE_MANAGEMENT_CLIENT_API_HEALTH_ENDPOINT:/health}
            uri: ${EVIDENCE_MANAGEMENT_CLIENT_API_BASEURL:http://localhost:4006}${service.evidence-management-client-api.health.context-path}
    service-auth-provider:
        health:
            context-path: /health
            uri: ${AUTH_PROVIDER_SERVICE_CLIENT_BASEURL:http://localhost:4502}${service.service-auth-provider.health.context-path}

auth:
    provider:
        service:
            client:
                port: 4502
                baseUrl: ${AUTH_PROVIDER_SERVICE_CLIENT_BASEURL:http://localhost:4502}
                tokenTimeToLiveInSeconds: 900

idam:
    s2s-auth:
        microservice: ${AUTH_PROVIDER_SERVICE_CLIENT_MICROSERVICE:sscs}
        totp_secret: ${AUTH_PROVIDER_SERVICE_CLIENT_KEY:AAAAAAAAAAAAAAAA}
        url: ${AUTH_PROVIDER_SERVICE_CLIENT_BASEURL:http://localhost:4502}

http:
    connect:
        timeout: 60000
        request:
            timeout: 60000

health:
    check:
        http:
            connect:
                timeout: 5000
                request:
                    timeout: 5000

info:
    app:
        name: ${spring.application.name}

pdf:
    test:
        enabled: false

document:
    templates:
        configurationList:
            -   templateName: FPRL-TEST-DOCUMENT.docx
                filename: TestTemplate.pdf
                document-generator: docmosis
    pdf:
        familyCourtImgKey: "familycourt"
        familyCourtImgVal: "[userImage:familycourt.png]"
        hmctsImgKey: "hmcts"
        hmctsImgVal: "[userImage:hmcts.png]"
        displayTemplateKey: "displayTemplateOnly"
        displayTemplateVal: "1"

template:
  relation:
    english:
      "male": "husband"
      "female": "wife"
    welsh:
      "male": "gŵr"
      "female": "gwraig"
      "husband": "gŵr"
      "wife": "gwraig"
  months:
    welsh:
      1: "Ionawr"
      2: "Chwefror"
      3: "Mawrth"
      4: "Ebrill"
      5: "Mai"
      6: "Mehefin"
      7: "Gorffennaf"
      8: "Awst"
      9: "Medi"
      10: "Hydref"
      11: "Tachwedd"
      12: "Rhagfyr"

service-auth-provider:
    service:
        stub:
            enabled: false

evidence-management-api:
    service:
        stub:
            enabled: false

documentation:
    swagger:
        enabled: true

spring:
    application:
        name: "div-dgs"
    resources:
        static-locations:

# GENERAL SPRING BOOT ACTUATOR CONFIG
# Context path for Spring Boot Actuator endpoints
# Allow actuator endpoints to be accessed without requiring authentication
# Enable default health indicators
# Enable disk space health check
# HEALTH ENDPOINT CONFIG
# Enable the health endpoint
# Enable sensitive health information
# Defines the URL of the health check to ${management.context-path}/health
# Caching period in milliseconds of health endpoint
# METRICS ENDPOINT CONFIG
# Enable the metrics endpoint
# Enable sensitive metrics information
management:
    endpoint:
        health:
            show-details: "ALWAYS"
            cache:
                time-to-live: 5000
    endpoints:
        web:
            base-path: /
            path-mapping:
                health: health
            exposure:
                include: info, health, metrics

logging:
    level:
        org.springframework.web: ERROR
        uk.gov.hmcts.reform.fprl.documentgenerator: DEBUG
        au.com.dius.pact: DEBUG
    pattern:
        console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n"

azure:
    app_insights_key: ${APPINSIGHTS_INSTRUMENTATIONKEY:false}

docmosis:
    service:
        pdf-service:
            accessKey: ${DOCMOSIS_SERVICE_ACCESS_KEY:23432}
            renderEndpoint: "/rs/render"
            uri: ${DOCMOSIS_SERVICE_BASE_URL:http://localhost:5501}${docmosis.service.pdf-service.renderEndpoint}
            devMode: ${DOCMOSIS_SERVICE_DEV_MODE_FLAG:false}

feature-toggle:
    toggle:
        feature_resp_solicitor_details: ${FEATURE_RESP_SOLICITOR_DETAILS:true}
