service:
  pdf-service:
    uri: ${PDF_SERVICE_BASEURL:http://cmc-pdf-service-aat.service.core-compute-aat.internal}/pdfs
    health:
      uri: ${PDF_SERVICE_BASEURL:http://cmc-pdf-service-aat.service.core-compute-aat.internal}/health
  service-auth-provider:
    health:
      context-path: /health
      uri: ${AUTH_PROVIDER_SERVICE_CLIENT_BASEURL:http://rpe-service-auth-provider-aat.service.core-compute-aat.internal}${service.service-auth-provider.health.context-path}

auth:
  provider:
    service:
      client:
          baseUrl: ${AUTH_PROVIDER_SERVICE_CLIENT_BASEURL:http://rpe-service-auth-provider-aat.service.core-compute-aat.internal}

case_document_am:
    url: ${CCD_CASE_DOCS_AM_API:http://ccd-case-document-am-api-aat.service.core-compute-aat.internal}

idam:
  s2s-auth:
    microservice: ${AUTH_PROVIDER_SERVICE_CLIENT_MICROSERVICE:fprl-dgs-api}
    totp_secret: ${AUTH_PROVIDER_SERVICE_CLIENT_KEY:replace_me}
    url: ${AUTH_PROVIDER_SERVICE_CLIENT_BASEURL:http://rpe-service-auth-provider-aat.service.core-compute-aat.internal}

docmosis:
  service:
    pdf-service:
      uri: ${DOCMOSIS_SERVICE_RENDER_URL:https://docmosis.aat.platform.hmcts.net/rs/render}
      accessKey: ${DOCMOSIS_SERVICE_ACCESS_KEY:replace_me}
